# Generated by Django 5.2.6 on 2025-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='Money Account Name')),
                ('currency_type', models.CharField(max_length=10, verbose_name='Currency')),
                ('macc_type', models.CharField(max_length=50, verbose_name='Account Type')),
                ('produkt', models.CharField(max_length=100, verbose_name='Produkt')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('trx_id', models.BigIntegerField(verbose_name='Transaction ID')),
                ('trx_type_id', models.IntegerField(verbose_name='Transaction Type ID')),
                ('trx_type_short', models.CharField(max_length=50, verbose_name='Transaction Type Short')),
                ('trx_type_name', models.CharField(max_length=100, verbose_name='Transaction Type Name')),
                ('buchungs_art_short', models.CharField(max_length=50, verbose_name='Booking Type Short')),
                ('buchungs_art_name', models.CharField(max_length=100, verbose_name='Booking Type Name')),
                ('val_date', models.DateField(verbose_name='Value Date')),
                ('trx_date', models.DateField(verbose_name='Transaction Date')),
                ('direction', models.SmallIntegerField(choices=[(1, 'Inflow'), (2, 'Outflow')], verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('trx_curry_id', models.IntegerField(verbose_name='Transaction Currency ID')),
                ('trx_curry_name', models.CharField(max_length=10, verbose_name='Transaction Currency Name')),
                ('text_short_creditor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text Short Creditor')),
                ('text_creditor', models.TextField(blank=True, null=True, verbose_name='Text Creditor')),
                ('text_short_debitor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text Short Debitor')),
                ('text_debitor', models.TextField(blank=True, null=True, verbose_name='Text Debitor')),
                ('point_of_sale_and_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='POS & Location')),
                ('acquirer_country_id', models.IntegerField(blank=True, null=True, verbose_name='Acquirer Country ID')),
                ('acquirer_country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acquirer Country')),
                ('card_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card ID')),
                ('cred_acc_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Creditor Account Text')),
                ('cred_iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='Creditor IBAN')),
                ('cred_addr_text', models.TextField(blank=True, null=True, verbose_name='Creditor Address')),
                ('cred_ref_nr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creditor Reference Number')),
                ('cred_info', models.TextField(blank=True, null=True, verbose_name='Creditor Info')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
            },
        ),
    ]
