# Generated by Django 5.2.6 on 2025-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_banktransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='trx_type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Transaction Type ID'),
        ),
    ]
