# Generated by Django 5.2.6 on 2025-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_banktransaction_trx_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='trx_curry_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Transaction Currency ID'),
        ),
    ]
