# Generated by Django 5.2.6 on 2025-09-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_banktransaction_trx_curry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.logo', verbose_name='URL'),
        ),
    ]
