# Generated by Django 5.2.6 on 2025-09-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_logo_banktransaction_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-val_date'], 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transactions'},
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.catagory', verbose_name='URL'),
        ),
    ]
