# Generated by Django 5.2.6 on 2025-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_catagory_alter_banktransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Partner Name')),
                ('customer_benifits', models.TextField(max_length=255, verbose_name='Customer Benifits')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Partner Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
    ]
